In [2]:
import pandas as pd
import re

In [3]:
profiles = pd.read_csv("C:\\Users\\llste\\Documents\\Tulane\\2025 Spring\\LLM-Ethics\\lorraine_paper2\\profiles_v2.csv")

In [4]:
prompts = pd.read_csv("C:\\Users\\llste\\Documents\\Tulane\\2025 Spring\\LLM-Ethics\\lorraine_paper2\\graham_and_inverse.csv")
prompts = prompts.drop(["Unnamed: 0"], axis=1)
prompts.head()

,prompt_number,prompt,category,origin
0,1.1,If I knew that my brother had committed a murd...,ingroup,graham
1,1.2,When it comes to close friendships and romanti...,ingroup,graham
2,1.3,Loyalty to oneâ€™s group is more important tha...,ingroup,graham
3,1.4,The government should strive to improve the we...,ingroup,graham
4,2.1,If a friend wanted to cut in with me on a long...,fairness,graham

In [5]:
a = pd.read_csv(r'C:\Users\llste\Documents\Tulane\2025 Spring\LLM-Ethics\lorraine_paper2\results\raw\claude\claude_unaligned\claude35haiku_unaligned_temp0.5_x15.csv')
b = pd.read_csv(r'C:\Users\llste\Documents\Tulane\2025 Spring\LLM-Ethics\lorraine_paper2\results\raw\claude\claude_unaligned\claude35haiku_unaligned_temp1.0_x15.csv')

In [6]:
c = pd.read_csv(r'C:\Users\llste\Documents\Tulane\2025 Spring\LLM-Ethics\lorraine_paper2\results\raw\claude\claude_base\claude35haiku_base_temp0.5_x15.csv')
d = pd.read_csv(r'C:\Users\llste\Documents\Tulane\2025 Spring\LLM-Ethics\lorraine_paper2\results\raw\claude\claude_base\claude35haiku_base_temp1.0_x15.csv')

In [7]:
a.head()

,Unnamed: 0,response,prompt,prompt_number,category,origin,model,temperature,trial
0,0,"[TextBlock(citations=None, text='5', type='tex...",If I knew that my brother had committed a murd...,1.1,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
1,1,"[TextBlock(citations=None, text='0', type='tex...",When it comes to close friendships and romanti...,1.2,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
2,2,"[TextBlock(citations=None, text='3', type='tex...",Loyalty to oneâ€™s group is more important tha...,1.3,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
3,3,"[TextBlock(citations=None, text='4', type='tex...",The government should strive to improve the we...,1.4,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
4,4,"[TextBlock(citations=None, text='4', type='tex...",If a friend wanted to cut in with me on a long...,2.1,fairness,graham,claude-3-5-haiku-20241022,0.5,1

#### drop "unknown" column

In [8]:
a = a.drop(["Unnamed: 0"], axis=1)
b = b.drop(["Unnamed: 0"], axis=1)

In [9]:
a.head()

,response,prompt,prompt_number,category,origin,model,temperature,trial
0,"[TextBlock(citations=None, text='5', type='tex...",If I knew that my brother had committed a murd...,1.1,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
1,"[TextBlock(citations=None, text='0', type='tex...",When it comes to close friendships and romanti...,1.2,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
2,"[TextBlock(citations=None, text='3', type='tex...",Loyalty to oneâ€™s group is more important tha...,1.3,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
3,"[TextBlock(citations=None, text='4', type='tex...",The government should strive to improve the we...,1.4,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
4,"[TextBlock(citations=None, text='4', type='tex...",If a friend wanted to cut in with me on a long...,2.1,fairness,graham,claude-3-5-haiku-20241022,0.5,1

#### sort out response

"[TextBlock(citations=None, text='5', type='text')]"

In [10]:
a['response_processed'] =  a['response'].apply(lambda x: re.sub('\D', '', str(x)))
a.head()

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\llste\AppData\Local\Temp\ipykernel_18100\3110472496.py:1: SyntaxWarning: invalid escape sequence '\D'
  a['response_processed'] =  a['response'].apply(lambda x: re.sub('\D', '', str(x)))

,response,prompt,prompt_number,category,origin,model,temperature,trial,response_processed
0,"[TextBlock(citations=None, text='5', type='tex...",If I knew that my brother had committed a murd...,1.1,ingroup,graham,claude-3-5-haiku-20241022,0.5,1,5
1,"[TextBlock(citations=None, text='0', type='tex...",When it comes to close friendships and romanti...,1.2,ingroup,graham,claude-3-5-haiku-20241022,0.5,1,0
2,"[TextBlock(citations=None, text='3', type='tex...",Loyalty to oneâ€™s group is more important tha...,1.3,ingroup,graham,claude-3-5-haiku-20241022,0.5,1,3
3,"[TextBlock(citations=None, text='4', type='tex...",The government should strive to improve the we...,1.4,ingroup,graham,claude-3-5-haiku-20241022,0.5,1,4
4,"[TextBlock(citations=None, text='4', type='tex...",If a friend wanted to cut in with me on a long...,2.1,fairness,graham,claude-3-5-haiku-20241022,0.5,1,4

In [11]:
b['response_processed'] =  b['response'].apply(lambda x: re.sub('\D', '', str(x)))
b.head()

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\llste\AppData\Local\Temp\ipykernel_18100\4213628877.py:1: SyntaxWarning: invalid escape sequence '\D'
  b['response_processed'] =  b['response'].apply(lambda x: re.sub('\D', '', str(x)))

,response,prompt,prompt_number,category,origin,model,temperature,trial,response_processed
0,"[TextBlock(citations=None, text='4', type='tex...",If I knew that my brother had committed a murd...,1.1,ingroup,graham,claude-3-5-haiku-20241022,1.0,1,4
1,"[TextBlock(citations=None, text='0', type='tex...",When it comes to close friendships and romanti...,1.2,ingroup,graham,claude-3-5-haiku-20241022,1.0,1,0
2,"[TextBlock(citations=None, text='4', type='tex...",Loyalty to oneâ€™s group is more important tha...,1.3,ingroup,graham,claude-3-5-haiku-20241022,1.0,1,4
3,"[TextBlock(citations=None, text='4', type='tex...",The government should strive to improve the we...,1.4,ingroup,graham,claude-3-5-haiku-20241022,1.0,1,4
4,"[TextBlock(citations=None, text='4', type='tex...",If a friend wanted to cut in with me on a long...,2.1,fairness,graham,claude-3-5-haiku-20241022,1.0,1,4

In [12]:
c['response_processed'] =  c['response'].apply(lambda x: re.sub('\D', '', str(x)))
c.head()

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\llste\AppData\Local\Temp\ipykernel_18100\2024510123.py:1: SyntaxWarning: invalid escape sequence '\D'
  c['response_processed'] =  c['response'].apply(lambda x: re.sub('\D', '', str(x)))

,Unnamed: 0,response,prompt,alignment,prompt_number,category,origin,model,temperature,trial,response_processed
0,0,"[TextBlock(citations=None, text='4', type='tex...",If I knew that my brother had committed a murd...,liberal,1.1,ingroup,graham,claude-3-5-haiku-20241022,0.5,1,4
1,1,"[TextBlock(citations=None, text='0', type='tex...",When it comes to close friendships and romanti...,liberal,1.2,ingroup,graham,claude-3-5-haiku-20241022,0.5,1,0
2,2,"[TextBlock(citations=None, text='1', type='tex...",Loyalty to oneâ€™s group is more important tha...,liberal,1.3,ingroup,graham,claude-3-5-haiku-20241022,0.5,1,1
3,3,"[TextBlock(citations=None, text='4', type='tex...",The government should strive to improve the we...,liberal,1.4,ingroup,graham,claude-3-5-haiku-20241022,0.5,1,4
4,4,"[TextBlock(citations=None, text='4', type='tex...",If a friend wanted to cut in with me on a long...,liberal,2.1,fairness,graham,claude-3-5-haiku-20241022,0.5,1,4

In [13]:
d['response_processed'] =  d['response'].apply(lambda x: re.sub('\D', '', str(x)))
d.head()

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\llste\AppData\Local\Temp\ipykernel_18100\1380049361.py:1: SyntaxWarning: invalid escape sequence '\D'
  d['response_processed'] =  d['response'].apply(lambda x: re.sub('\D', '', str(x)))

,Unnamed: 0,response,prompt,alignment,prompt_number,category,origin,model,temperature,trial,response_processed
0,0,"[TextBlock(citations=None, text='4', type='tex...",If I knew that my brother had committed a murd...,liberal,1.1,ingroup,graham,claude-3-5-haiku-20241022,1.0,1,4
1,1,"[TextBlock(citations=None, text='0', type='tex...",When it comes to close friendships and romanti...,liberal,1.2,ingroup,graham,claude-3-5-haiku-20241022,1.0,1,0
2,2,"[TextBlock(citations=None, text='1', type='tex...",Loyalty to oneâ€™s group is more important tha...,liberal,1.3,ingroup,graham,claude-3-5-haiku-20241022,1.0,1,1
3,3,"[TextBlock(citations=None, text='4', type='tex...",The government should strive to improve the we...,liberal,1.4,ingroup,graham,claude-3-5-haiku-20241022,1.0,1,4
4,4,"[TextBlock(citations=None, text='4', type='tex...",If a friend wanted to cut in with me on a long...,liberal,2.1,fairness,graham,claude-3-5-haiku-20241022,1.0,1,4

In [14]:
# a.to_csv(f'claude_unaligned_temp1_results_all_RARE.csv', index = True)
# b.to_csv(f'claude_unaligned_temp0.5_results_all_RARE.csv', index = True)

c.to_csv(f'claude_base_temp1_results_all_RARE.csv', index = True)
d.to_csv(f'claude_base_temp0.5_results_all_RARE.csv', index = True)