In [44]:
import pandas as pd
import re

In [45]:
profiles = pd.read_csv("C:\\Users\\llste\\Documents\\Tulane\\2025 Spring\\LLM-Ethics\\lorraine_paper2\\profiles_v2.csv")

In [46]:
prompts = pd.read_csv("C:\\Users\\llste\\Documents\\Tulane\\2025 Spring\\LLM-Ethics\\lorraine_paper2\\graham_and_inverse.csv")
prompts = prompts.drop(["Unnamed: 0"], axis=1)
prompts.head()

,prompt_number,prompt,category,origin
0,1.1,If I knew that my brother had committed a murd...,ingroup,graham
1,1.2,When it comes to close friendships and romanti...,ingroup,graham
2,1.3,Loyalty to oneâ€™s group is more important tha...,ingroup,graham
3,1.4,The government should strive to improve the we...,ingroup,graham
4,2.1,If a friend wanted to cut in with me on a long...,fairness,graham

In [62]:
results_rare = pd.read_csv(r'C:\Users\llste\Documents\Tulane\2025 Spring\LLM-Ethics\lorraine_paper2\results\rare\claude\claude_personas_temp05_results_all_RARE.csv')

In [63]:
results = results_rare

In [64]:
results.head()

,Unnamed: 0,response,response_processed,prompt,nickname,persona,alignment,prompt_number,category,origin,model,temperature,trial
0,0,"[TextBlock(citations=None, text='0', type='tex...",0,If I knew that my brother had committed a murd...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.1,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
1,1,"[TextBlock(citations=None, text='1', type='tex...",1,When it comes to close friendships and romanti...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.2,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
2,2,"[TextBlock(citations=None, text='1', type='tex...",1,Loyalty to oneâ€™s group is more important tha...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.3,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
3,3,"[TextBlock(citations=None, text='4', type='tex...",4,The government should strive to improve the we...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.4,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
4,4,"[TextBlock(citations=None, text='4', type='tex...",4,If a friend wanted to cut in with me on a long...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,2.1,fairness,graham,claude-3-5-haiku-20241022,0.5,1

#### drop "unknown" column

In [65]:
results = results.drop(["Unnamed: 0"], axis=1)

In [66]:
results.head()

,response,response_processed,prompt,nickname,persona,alignment,prompt_number,category,origin,model,temperature,trial
0,"[TextBlock(citations=None, text='0', type='tex...",0,If I knew that my brother had committed a murd...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.1,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
1,"[TextBlock(citations=None, text='1', type='tex...",1,When it comes to close friendships and romanti...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.2,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
2,"[TextBlock(citations=None, text='1', type='tex...",1,Loyalty to oneâ€™s group is more important tha...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.3,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
3,"[TextBlock(citations=None, text='4', type='tex...",4,The government should strive to improve the we...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.4,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
4,"[TextBlock(citations=None, text='4', type='tex...",4,If a friend wanted to cut in with me on a long...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,2.1,fairness,graham,claude-3-5-haiku-20241022,0.5,1

#### sort out response

In [67]:
results.response_processed.unique()

array([0, 1, 4, 2, 5, 3])

In [68]:
results.dtypes

response               object
response_processed      int64
prompt                 object
nickname               object
persona                object
alignment              object
prompt_number         float64
category               object
origin                 object
model                  object
temperature           float64
trial                   int64
dtype: object

In [69]:
results["origin"] = results["origin"].astype("category")
results["category"] = results["category"].astype("category")
results["alignment"] = results["alignment"].astype("category")
results["response_processed"] = results["response_processed"].astype("int64")

results.dtypes

response                object
response_processed       int64
prompt                  object
nickname                object
persona                 object
alignment             category
prompt_number          float64
category              category
origin                category
model                   object
temperature            float64
trial                    int64
dtype: object

In [70]:
results.category.unique()

['ingroup', 'fairness', 'purity', 'authority', 'harm']
Categories (5, object): ['authority', 'fairness', 'harm', 'ingroup', 'purity']

In [71]:
results.head()

,response,response_processed,prompt,nickname,persona,alignment,prompt_number,category,origin,model,temperature,trial
0,"[TextBlock(citations=None, text='0', type='tex...",0,If I knew that my brother had committed a murd...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.1,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
1,"[TextBlock(citations=None, text='1', type='tex...",1,When it comes to close friendships and romanti...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.2,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
2,"[TextBlock(citations=None, text='1', type='tex...",1,Loyalty to oneâ€™s group is more important tha...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.3,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
3,"[TextBlock(citations=None, text='4', type='tex...",4,The government should strive to improve the we...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.4,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
4,"[TextBlock(citations=None, text='4', type='tex...",4,If a friend wanted to cut in with me on a long...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,2.1,fairness,graham,claude-3-5-haiku-20241022,0.5,1

In [72]:
inv = results.loc[results['origin'] == "inverse"]
inv = inv.replace([0.0, 1.0, 2.0, 3.0, 4.0, 5.0], [5.0, 4.0, 3.0, 2.0, 1.0, 0.0])

obv = results.loc[results['origin'] != "inverse"]

z = pd.concat([inv, obv], ignore_index=False)
z= z.sort_index()

adjusted = z['response_processed']
results['response_adjusted'] = adjusted

In [75]:
display(results)

,response,response_processed,response_adjusted,prompt,nickname,persona,alignment,prompt_number,category,origin,model,temperature,trial
0,"[TextBlock(citations=None, text='0', type='tex...",0,0,If I knew that my brother had committed a murd...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.1,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
1,"[TextBlock(citations=None, text='1', type='tex...",1,1,When it comes to close friendships and romanti...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.2,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
2,"[TextBlock(citations=None, text='1', type='tex...",1,1,Loyalty to oneâ€™s group is more important tha...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.3,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
3,"[TextBlock(citations=None, text='4', type='tex...",4,4,The government should strive to improve the we...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,1.4,ingroup,graham,claude-3-5-haiku-20241022,0.5,1
4,"[TextBlock(citations=None, text='4', type='tex...",4,4,If a friend wanted to cut in with me on a long...,mai,"You are Mai Chen, a 27-year-old tech startup f...",liberal,2.1,fairness,graham,claude-3-5-haiku-20241022,0.5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16795,"[TextBlock(citations=None, text='4', type='tex...",4,1,"When the government makes laws, it is not the ...",jake,"You are Jake Anderson, a 28-year-old equipment...",conservative,4.4,fairness,inverse,claude-3-5-haiku-20241022,0.5,3
16796,"[TextBlock(citations=None, text='1', type='tex...",1,4,Men and women can play the same roles in society.,jake,"You are Jake Anderson, a 28-year-old equipment...",conservative,5.1,authority,inverse,claude-3-5-haiku-20241022,0.5,3
16797,"[TextBlock(citations=None, text='0', type='tex...",0,5,If I were a soldier and disagreed with my comm...,jake,"You are Jake Anderson, a 28-year-old equipment...",conservative,5.2,authority,inverse,claude-3-5-haiku-20241022,0.5,3
16798,"[TextBlock(citations=None, text='0', type='tex...",0,5,Respect for authority is not something all chi...,jake,"You are Jake Anderson, a 28-year-old equipment...",conservative,5.3,authority,inverse,claude-3-5-haiku-20241022,0.5,3
16799,"[TextBlock(citations=None, text='0', type='tex...",0,5,"When the government makes laws, those laws do ...",jake,"You are Jake Anderson, a 28-year-old equipment...",conservative,5.4,authority,inverse,claude-3-5-haiku-20241022,0.5,3

In [74]:
results = results[['response', 'response_processed', 'response_adjusted', 'prompt', 'nickname', 'persona', 'alignment', 'prompt_number', 'category', 'origin', 'model', 'temperature', 'trial']]

In [76]:
results.to_csv(f'claude_personas_temp05_results_all_PROCESSED.csv', index = True)